language: go
matrix:
  include:
    - go: 1.10.x
    - go: 1.11.x
    - go: tip
  allow_failures:
    - go: tip
dist: xenial
sudo: false
before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
install:
  - dep ensure
  - go build -tags=nogpu
script:
  - echo "Skip tests..."
after_script:
  - go test -tags=nogpu -race -v .
